services:
  web:
    build: .
    container_name: django_app
    command: >
      sh -c "while ! nc -z db 3306; do sleep 2; done &&
             python manage.py migrate &&
             gunicorn storebackend.wsgi:application --bind 0.0.0.0:8000 --timeout 90 --workers 3"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - store-network
  db:
    image: mysql:8.0
    container_name: mysql_db
    hostname: db
    restart: always
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - store-network
networks:
  store-network:
    driver: bridge
volumes:
  mysql_data:
