# Generated by Django 5.2.5 on 2025-09-07 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0002_rename_country_address_district_remove_address_state_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='backendapi.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapi.product')),
            ],
        ),
    ]
