# Generated by Django 5.2.5 on 2025-09-11 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0004_order_delivery_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
